my_blog/blog/urls.py
from django.urls import path
from blog import views
from .views import post_delete
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),
    path('category/', views.category, name='category'),
    path('post/<int:id>',views.post_detail, name='post_detail'),
    path('post/new', login_required(views.post_new), name='post_new'),
    path('post/<int:id>/update/',  views.post_update, name='post_update'),
    path('post/<int:pk>/delete/',  login_required(post_delete.as_view()), name='post_delete'),
    path('profile', views.profile, name='profile'),
    path('profile/<int:id>/update/', views.profile_update, name='profile_update'),
    path('account/signup', views.sign_up, name='sign_up'),
]
# Path of media files
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
#    path('', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

my_blog/blog/models.py
from django.db import models
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class User(AbstractUser):
    age = models.IntegerField(null=True, blank=True)
    telephone = models.CharField(max_length=15, blank=True, null=True)
    birthday = models.DateField(null=True)
    avatar = models.ImageField(default='default.jpg', upload_to='profile/')

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    parent = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    category = models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.category

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)
    category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True)
    parent = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    body = RichTextUploadingField()
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
#        return reverse('home')
        return  reverse('post_detail', args=[str(self.id)])

class Comment(models.Model):
    title = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = RichTextField()
    def __str__(self):
        #return self.comment
        return str(self.title)

my_blog/blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import User, Post, Category, SubCategory, Comment
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = UserChangeForm.Meta.fields

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        #fields = ['username', 'email', 'telephone', 'password1', 'password2']
        fields = UserCreationForm.Meta.fields

class ProfileUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'telephone', 'avatar']

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title','parent','category','body']

class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['name']

class SubCategoryForm(ModelForm):
    class Meta:
        model = SubCategory
        fields = ['category']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

my_blog/blog/views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, Category, SubCategory, User
from .forms import SignUpForm, ProfileUpdateForm, PostForm, CategoryForm, CommentForm
from django.views.generic import ListView, DetailView, CreateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages, auth
from django.db.models import Q

# Set global query.
all_category = Category.objects.all()
all_subcategory = SubCategory.objects.all()

def home(request):
    all_post = Post.objects.all()
    context = {
        'all_post': all_post, 
        'all_category': all_category, 
        'all_subcategory': all_subcategory
    }
    return render(request, 'home.html', context)

def about(request):
    return render(request, 'about.html')

def category(request):
    return render(request, 'category.html' ,{'all_category': all_category})

def search(request):
    search_result = []
    query = request.GET.get('q')
#    if query == '':
#        query = ''
    search_result = Post.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))
    return render(request, 'search_result.html', {'search_result': search_result})

def post_detail(request, id):
    #post = Post.objects.get(id=id)
    post = get_object_or_404(Post, id=id)
    comments = Comment.objects.filter(title_id=id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.title = post
            comment.author = request.user
            comment.save()
            return redirect('post_detail', id=id)  
    else:
        form = CommentForm()
        context = {
            'post': post, 
            'comments': comments,
            'form': form,
            'all_category': all_category,
            'all_subcategory': all_subcategory
        }
        return render(request, 'post_detail.html', context)

def sign_up(request):
    if request.method == 'GET':
        context = {'form': SignUpForm()}
        return render(request, 'registration/sign_up.html', context)
    elif request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'registration/sign_up.html', context)

def profile(request):
    return render(request, 'profile_detail.html')

def profile_update(request, id):
    if id != request.user.id:
        return redirect('home')
    else:
        profile = get_object_or_404(User, id=id)
        if request.method == 'GET':
            context = {'form': ProfileUpdateForm(instance=profile), 'id': id}
            return render(request,'profile_update.html', context)
        elif request.method == 'POST':
            form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
            if form.is_valid():
                form.save()
                return redirect('profile')
        else:
            return render(request,'profile_update.html', context)

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post_detail', id=post.id)
    else:
        context = {'form': PostForm()}
        return render(request, 'post_new.html', context)

def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    if (request.user == post.author or request.user.is_superuser):
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                form.save()
                return redirect('post_detail', id=id)
        else:
            context = {'form': PostForm(instance=post), 'id': id}
            return render(request, 'post_update.html', context)
    else:
        return redirect('post_detail', id=id)

class post_delete(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

    

my_blog/blog/templates/category.html
<!-- templates/home.html -->
{% extends 'master.html' %}
{% block title%}Category{% endblock %}
{% block content %}
  {% for category in all_category %}
    <p>{{ category.name }}</p>
      {% for sub in category.subcategory_set.all %}
        <p>{{ sub.category }}</p>
        <ul>
          {% for post in sub.post_set.all %}
            <li><p>{{ post.title }}</p></li>
          {% endfor %}
          </ul>
      {% endfor %}
  {% endfor %}
    <p></p>
{% endblock %}

my_blog/blog/templates/home.html
<!-- templates/home.html -->
{% extends 'master.html' %}
{% block title%}Home pages{% endblock %}
{% block content %}
  {% for x in all_post reversed %}
  <div class="bg-light mb-3 p-2 rounded">
    <h3><a style="text-decoration: none;" href="{% url 'post_detail' x.id %}">{{x.title|title}}</a></h3>
    <p class="text-muted" style="font-size: small;">by QHOA Date: 11.11.22</p>
    <p class="">{{x.body|truncatechars_html:280|safe}}</p>
    <p align="left">
      <a class="btn-sm btn-success" href="{% url 'post_detail' x.id %}" role="button">Details &raquo;</a>
    </p>
  </div>
  {% endfor %}
{% endblock %}

my_blog/blog/templates/master size.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/sidebars.css' %}">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
  <header class="p-3 bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">My Blog</a>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            {% if user.is_authenticated %}
            <li><a href="{% url 'profile' %}" class="nav-link px-2 text-secondary">Profile</a></li>
            <li><a href="#" class="nav-link px-2 text-secondary dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Accounts</a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'password_reset' %}">Reset Password</a></li>
                {% if user.is_superuser %}
                <li><a class="dropdown-item" href="/admin">Admin Panel</a></li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            <li><a href="{% url 'about' %}" class="nav-link px-2 text-secondary">About</a></li>
          </ul>
  
          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'search' %}" method="get" >
            <input type="text" name="q" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
          </form>
  
          <div class="text-end">
            {% if user.is_anonymous %}
            <a href="{% url 'login' %}" role="button" class="btn btn-outline-light me-2">Login</a>
            <a href="{% url 'sign_up' %}" role="button" class="btn btn-warning">Sign-up</a>
            {% else %}
            <a href="{% url 'logout' %}" role="button" class="btn btn-outline-light me-2">Logout</a>
            {% endif %}
          </div>
        </div>
      </div>
    </header>
<div class="container">
<div class="row">
  <div class="col-md-1">
  </div>
  <div class="px-5 col-md-10 bg-light">
    {% block content %}
    {% endblock %}
  </div>
  <div class="col-md-1">
  </div>
</div>
</div>
</body>
</html>

my_blog/blog/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <link rel="stylesheet" href="{% static 'css/base.css' %}">  -->
    <link rel="stylesheet" href="{% static 'css/sidebars.css' %}">
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <header class="p-3 bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">My Blog</a>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            {% if user.is_authenticated %}
            <li><a href="{% url 'profile' %}" class="nav-link px-2 text-secondary">Profile</a></li>
            <li><a href="#" class="nav-link px-2 text-secondary dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Accounts</a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'password_reset' %}">Reset Password</a></li>
                {% if user.is_superuser %}
                <li><a class="dropdown-item" href="/admin">Admin Panel</a></li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            <li><a href="{% url 'about' %}" class="nav-link px-2 text-secondary">About</a></li>
          </ul>
  
          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'search' %}" method="get" >
            <input type="text" name="q" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
          </form>
  
          <div class="text-end">
            {% if user.is_anonymous %}
            <a href="{% url 'login' %}" role="button" class="btn btn-outline-light me-2">Login</a>
            <a href="{% url 'sign_up' %}" role="button" class="btn btn-warning">Sign-up</a>
            {% else %}
            <a href="{% url 'logout' %}" role="button" class="btn btn-outline-light me-2">Logout</a>
            {% endif %}
          </div>
        </div>
      </div>
    </header>
<div class="container">
  <div class="row">
    <div class="col-md-2 border border-light bg-white">
      {% if user.is_authenticated %}
      <div>
        <p align="center">Hi, <strong>{{user.username}}</strong>!</p>
        <p align="center"><img src="{{MEDIA_URL}}{{user.avatar}}" class="img-thumbnail rounded-circle border-0" alt=""></p>
      </div>
      {% endif %}
      <div class="m-1 p-2 bg-secondary rounded-3 text-white">Main</div>
      <ul class="list-unstyled ps-0">
              <li class="mb-1">
                <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
                  Home
                </button>
                <div class="collapse show" id="home-collapse">
                  <ul class="btn-toggle-nav list-unstyled fw-normal pb-1">
                    <li><a href="{% url 'home' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Main Pages</a></li>
                    <li><a href="{% url 'post_new' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">News Post</a></li>
                  </ul>
                </div>
              </li>
  {% for category in all_category %}
    <div class="p-2 bg-secondary rounded-3 text-white">{{category.name}}</div>
      {% for sub in category.subcategory_set.all %}
        {% if sub.post_set.all.count > 0 %}
          <p class="m-0">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#{{ sub.category|slugify }}-collapse" aria-expanded="true">
            {{ sub.category }}<span class="small text-muted">({{sub.post_set.all.count}})</span>
            </button>
          </p>
        {% endif %}
        <div class="collapse show" id="{{ sub.category|slugify }}-collapse">
        <ul>
        {% for post in sub.post_set.all %}
          <p class="m-0"><li><a href="{% url 'post_detail' post.id %}" class="small"> {{post.title|title}}</a></li></p>
        {% endfor %}
        </ul>
        </div>
      {% endfor %}
  {% endfor %}
      </ul>
    </div>
    <div class="col-md-10">
        {% block content %}
        {% endblock %}
    </div>
  </div>
</div>
</body>
</html>

my_blog/blog/templates/post_delete.html
<!-- templates/home.html -->
{% extends 'master.html' %}
{% block title%}Delete Post{% endblock %}
{% block content %}
<div class="">
    <h1>Delete Post</h1>
      <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure to delete <span style="color: red;font-weight: bold;"> "{{ post.title|title }}"</span> ?</p>
      </form>
      <p>
        <input class="btn btn-success" type="submit" value="Delete">
      </p>
</div>
{% endblock %}

my_blog/blog/templates/post_detail.html
<!-- templates/home.html -->
{% extends 'master.html' %}
{% block title%}Blog Post{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="">
      <h1>{{post.title|title}}</h1>
      <p class="">{{post.body|safe}}</p>
      <hr>
      {% if request.user == post.author or user.is_superuser %}
      <p>
        
          <a class="btn btn-success" role="button" href="{% url 'post_update' post.id %}">Update</a>
          <a class="btn btn-success" role="button" href="{% url 'post_delete' post.id %}">Delete</a>
      </p>
      <hr>
      {% endif %}
      {% for x in comments %}
      <figure>
        <blockquote class="blockquote-footer">
          Author: <cite title="Source Title">{{x.author}}</cite>
        </blockquote>
        <figcaption class="blockquote">
          <small><em>{{x.body|safe}}</em></small>
        </figcaption>
      </figure>
      <hr>
      {% endfor %}
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {{ form.media }}
        <p>
          <input class="btn btn-success" type="submit" value="Comment">
        </p>
      </form>
    </div>
{% endblock %}

my_blog/blog/templates/post_new.html
<!-- templates/home.html -->
{% extends 'master.html' %}
{% block title%}Content of blog{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="">
    <h1>New Post</h1>
      <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        {{ form.media }}
        <p>
          <input class="btn btn-success" type="submit" value="Save">
          <input class="btn btn-success" type="reset" value="Reset">
        </p> 
      </form> 
  </div>
{% endblock %}

my_blog/blog/templates/post_update.html
<!-- templates/home.html -->
{% extends 'master.html' %}
{% block title%}Content of blog{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="">
    <h1>Update Post</h1>
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {{ form.media }}
        <p>
          <input class="btn btn-success" type="submit" value="Update">
        </p>
      </form>
</div>
{% endblock %}

my_blog/blog/templates/profile_detail.html
<!-- templates/home.html -->
{% extends 'master size.html' %}
{% block title%}User Profile{% endblock %}
{% block content %}
<div class="container">
  <div class="main-body">

        <div class="row gutters-sm">
          <div class="col-md-4 mb-3">
            <div class="card">
              <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                  <img src="{{MEDIA_URL}}{{user.avatar}}" alt="Admin" class="rounded-circle" width="150">
                  <div class="mt-3">
                    <h4>{{user.username}}</h4>
                    {% if user.is_superuser %}
                    <p class="text-secondary mb-1">Admin</p>
                    {% else %}
                    <p class="text-secondary mb-1">User</p>
                    {% endif %}
                    <!--<p class="text-muted font-size-sm">Bay Area, San Francisco, CA</p>
                    <button class="btn btn-primary">Follow</button>
                    <button class="btn btn-outline-primary">Message</button>-->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="card mb-3">
              <div class="card-body">
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">User Name</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    {{user.username}}
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">First Name</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    {{user.first_name}}
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Last Name</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    {{user.last_name}}
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Email</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    {{user.email}}
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Phone</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    {{user.telephone}}
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Age</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    {{user.age}}
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h6 class="mb-0">Birthday</h6>
                  </div>
                  <div class="col-sm-9 text-secondary">
                    {{user.birthday}}
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-12">
                    <a class="btn btn-info " target="__blank" href="{% url 'profile_update' user.id %}">Edit</a>
                  </div>
                </div>
              </div>
            </div>

            <!--<div class="row gutters-sm">
              <div class="col-sm-6 mb-3">
                <div class="card h-100">
                  <div class="card-body">
                    <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                    <small>Web Design</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>Website Markup</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>One Page</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>Mobile Template</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>Backend API</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-6 mb-3">
                <div class="card h-100">
                  <div class="card-body">
                    <h6 class="d-flex align-items-center mb-3"><i class="material-icons text-info mr-2">assignment</i>Project Status</h6>
                    <small>Web Design</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>Website Markup</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 72%" aria-valuenow="72" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>One Page</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 89%" aria-valuenow="89" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>Mobile Template</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 55%" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <small>Backend API</small>
                    <div class="progress mb-3" style="height: 5px">
                      <div class="progress-bar bg-primary" role="progressbar" style="width: 66%" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>-->



          </div>
        </div>

      </div>
  </div>
{% endblock %}

my_blog/blog/templates/profile_update.html
<!-- templates/home.html -->
{% extends 'master size.html' %}
{% block title%}User Profile{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
  <div class="main-body">

        <div class="row gutters-sm">
          <div class="col-md-4 mb-3">
            <div class="card">
              <div class="card-body">
                <div class="d-flex flex-column align-items-center text-center">
                  <img src="{{MEDIA_URL}}{{user.avatar}}" alt="Admin" class="rounded-circle" width="150">
                  <div class="mt-3">
                    <h4>{{user.username}}</h4>
                    {% if user.is_superuser %}
                    <p class="text-secondary mb-1">Admin</p>
                    {% else %}
                    <p class="text-secondary mb-1">User</p>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-8">
            <div class="card mb-3">
              <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                  {{ form|crispy }}
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <input class="btn btn-primary" type="submit" value="Update">
                  </div>
                </div>
              </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}

my_blog/blog/templates/search_result.html
<!-- templates/home.html -->
{% extends 'master.html' %}
{% block title%}Home pages{% endblock %}
{% block content %}
  {% for x in search_result %}
  <div class="bg-light m-3 p-2 rounded">
    <h3><a href="{% url 'post_detail' x.id %}">{{x.title|title}}</a></h3>
    <p class="">{{ x.body|truncatechars_html:200|safe}}</p>
    <p align="left">
      <a class="btn-sm btn-success" href="{% url 'post_detail' x.id %}" role="button">Details &raquo;</a>
    </p>
  </div>
  {% endfor %}
{% endblock %}